blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    about: Please report security issues via GitHub Security Advisories.
    url: https://github.com/SolLabsHQ/.github/security/advisories
